Consider making kcidb-validate output validated reports #145
kernelci/kcidb pull request #239
Opened 2021-11-20 12:42 UTC by mharyam

Close #145 

- Add print to kcidb-validate to output reports after they were validated

2021-11-22 13:46 UTC, spbnick commented
Thank you, Maryam. Please "ping" me in a comment or on Slack, when you're ready for review.

2021-11-24 08:24 UTC, mharyam commented
> Thank you, Maryam. Please "ping" me in a comment or on Slack, when you're ready for review.

Thank you 
I will

2021-12-07 15:41 UTC, spbnick requested changes
Yep, that's basically what needs to be done. However, could you please re-implement this using `misc.json_dump_stream()` and `misc.OutputArgumentParser`, similarly to how `upgrade_main()` does it? This way the tool would act more like others.

2021-12-08 16:43 UTC, spbnick commented on kcidb/__init__.py
> +            args.schema_version.upgrade(io.schema.validate(data), copy=False)
This changes the function and the `kcidb-validate` tool to also upgrade the data, which is not in the issue you're trying to fix: https://github.com/kernelci/kcidb/issues/145

Your first attempt was basically fine, and I'm just asking you to make the tool's interface match the other tools.

Ping me on Slack, if you need help figuring this out.

2021-12-10 12:13 UTC, spbnick requested changes
Ah, this is better :smiley: The code itself is correct, but tests need more work.

The `assertExecutes` function is quite involved. Basically, it imitates execution of a separate program given its "main" function. We need to imitate it, because we need to be able to run tests without installing KCIDB, and the executables are only created by setuptools upon installation. I.e. there are no executables in the source code. So, `assertExecutes` creates a new process calling its `main` function, feeds it the specified standard input, captures the produced stdout and stderr, and the exit status, and then checks that they match the specified requirements.

So, e.g. this line:
```
self.assertExecutes('', "kcidb.validate_main")
```
Creates a new process, which calls the `kcidb.validate_main` function in the same manner as `kcidb-validate` would, feeds it the (default) empty string through standard input (stdin), reads its standard output (stdout) and standard error (stderr) streams, as well as its exit status, and checks that they match the (default) requirements of "", "", and 0 respectively.

Hope this helps you understand what the test is doing :)

Please also try running `kcidb-validate` with various inputs both before and after your change to get a feel of what it does, and what your change does.

2021-12-10 12:13 UTC, spbnick commented on kcidb/unittest.py
> +        if not re.match(stdout_re, result.stdout, re.DOTALL):
This is side-stepping the problem. The use of `fullmatch()` is intentional here. Something that should be documented in the function's docstring, though. Please revert this change, and if you can figure out how, document that the regular expressions are matched fully.

2021-12-10 12:13 UTC, spbnick commented on test_kcidb.py
> +                            stdout_re='{"version": {"major": 4, "minor": 0}}')
Ah, you're getting there!

2021-12-13 12:59 UTC, spbnick commented
Heey, this is very good, looks great!

However, could you please amend the commit subject to match what's being done? Something like "Output validated reports in kcidb-validate".

Also, do you think you could add another commit on top adding two more cases to the test:
* validate three valid reports in a row (in a single execution of `kcidb-validate`);
* validate three reports in a row, where the middle one is invalid, but the two others are valid?

It would be best if all three were different, in both cases, so we could make sure the ordering is correct and the right one is considered invalid.

2021-12-14 09:30 UTC, spbnick commented
This looks very nice! Thank you, Maryam! All code and tests are fine, but could you please amend commit subjects to better describe the changes?

The first one could be something like "Output validated reports in kcidb-validate", and the second something like "tests: Add two more kcidb-validate cases".

2021-12-14 14:33 UTC, mharyam commented
> This looks very nice! Thank you, Maryam! All code and tests are fine, but could you please amend commit subjects to better describe the changes?
> 
> The first one could be something like "Output validated reports in kcidb-validate", and the second something like "tests: Add two more kcidb-validate cases".

Done

2021-12-14 14:41 UTC, spbnick commented
Looks good to me. Thanks a lot! Merging.

2021-12-14 14:41 UTC, merged