Misc fixes
kernelci/kcidb pull request #304
Opened 2022-04-28 14:47 UTC by spbnick

This introduces a host of minor fixes and improvements done during the work on table partitioning and query time-limiting.

2022-04-28 14:47 UTC, spbnick commented
@mrbazzan, do you think you could take a stab at reviewing these?

2022-04-28 16:08 UTC, mrbazzan commented
> @mrbazzan, do you think you could take a stab at reviewing these?

Sure. Anything you want me to especially look out for?

2022-04-29 09:38 UTC, spbnick commented
> > @mrbazzan, do you think you could take a stab at reviewing these?
> 
> Sure. Anything you want me to especially look out for?

No, just please try to find anything wrong with it, if you can. Thank you :relaxed:

2022-05-01 23:44 UTC, mrbazzan requested changes

2022-05-01 23:44 UTC, mrbazzan commented on kcidb/db/sqlite/schema.py
>          assert unpack is None or callable(unpack)
Shouldn't `pack` and `unpack` parameters be removed from the constructor? I also think the validation statement should be removed.

2022-05-01 23:44 UTC, mrbazzan commented on kcidb/misc.py
> +        The non-negative integer, or  parsed out of the string.
Incoherent `Returns:`

Should be something like: `The timestamp parsed out of the string.`

2022-05-01 23:46 UTC, mrbazzan commented
> @mrbazzan, do you think you could take a stab at reviewing these?

Looks good aside the two suggested changes.

2022-05-02 13:20 UTC, spbnick commented
Thanks a lot, @mrbazzan, both are good catches! Should be fixed now, please check :relaxed:

2022-05-02 14:00 UTC, mrbazzan commented
@spbnick LGTM!

2022-05-02 14:13 UTC, spbnick commented
Thanks, Abdulwasiu, merging!

2022-05-02 14:13 UTC, merged