modify client to notice schema changes
kernelci/kcidb pull request #411
Opened 2023-03-25 18:16 UTC by NikkyXO

2023-03-25 22:31 UTC, NikkyXO commented
i had to initialize the database in the constructor, because one of the checks kept failing, even though i already had a separate commit for that @spbnick

2023-03-27 16:45 UTC, spbnick commented on kcidb/db/__init__.py
> +                        or None.
The method shouldn't accept a new database string, as its whole purpose is to recreate the client for the existing database. If the user wants to connect to another database, they should just create a new client. Please remove the parameter.

2023-03-27 16:49 UTC, spbnick commented on kcidb/db/__init__.py
> +            A new client object
No, this method should not create a new client. We can already do that ourselves. What we need to do is to keep the same `Client` object, but make it re-create the driver instance it's using (`self.driver`).

Essentially you can move the `self.driver = ...` assignment and the following assertion from `__init__()` here, and then call this method from `__init__()` instead.

2023-03-27 16:52 UTC, spbnick commented on kcidb/db/__init__.py
> +        self.database = database
Normally, what you'd do in this situation, is to cherry-pick the commit you need into this PR's branch, and then add your changes in a separate commit on top, mentioning in the PR description, that it requires that other PR to get merged first. Then you drop the cherry-picked commit after that PR is merged by rebasing your branch on latest `main` and pushing to the PR again.

But you can leave this as is for this PR and focus on the main change for now.

2023-03-28 13:39 UTC, spbnick requested changes

2023-03-28 13:39 UTC, spbnick commented on kcidb/db/__init__.py
> +        return Client(self.database)
This just creates a new `Client()` instance. This method should instead modify the instance it's called for. It should create a new driver instance and store it in `self.driver`. It should not return anything. As I said in my previous comment:

> Essentially you can move the self.driver = ... assignment and the following assertion from __init__() here, and then call this method from __init__() instead.

2023-03-28 13:39 UTC, spbnick commented on kcidb/db/__init__.py
> +        self.database = database
Now that [your PR](https://github.com/kernelci/kcidb/pull/409) adding this is merged, you can rebase your PR on top of latest main, and get rid of this change in it.

2023-03-28 15:13 UTC, closed without merging