doc: add content from legacy documentation in kernelci-project
kernelci/kcidb pull request #455
Opened 2023-08-12 19:47 UTC by gctucker

As the documentation in kernelci-project is being updated to cover the new API & Pipeline, some content is being moved to a Legacy section. As a result, consolidate the KCIDB documentation on the KCIDB section main page to decouple it from the rest of the rework.

There is now a direct mention of KCIDB on the documentation landing page on kernelci.org/doc with the overall KernelCI architecture diagram.  Then most of the KCIDB-specific parts are now being moved to the KCIDB section.  Once all the changes have landed, we might revisit this again and add KCIDB mentions in more places if needed.

Depends on https://github.com/kernelci/kernelci-project/pull/230
Depends on https://github.com/kernelci/kernelci-project/pull/232

2023-08-12 19:53 UTC, gctucker commented
Deployed on staging static website:
https://static.staging.kernelci.org/docs/kcidb/

See also the KCIDB mention on the top-level page:
https://static.staging.kernelci.org/docs/

2023-08-15 10:55 UTC, spbnick requested changes
Thanks, Guillaume! I have just two small comments/requests, otherwise I think it's good to go.

2023-08-15 10:55 UTC, spbnick commented on doc/_index.md
> +KCIDB:
Maybe add ", including" on the end?

2023-08-15 10:55 UTC, spbnick commented on doc/_index.md
> +details about the latest status of data submitters.
Perhaps drop this paragraph, since I haven't been sending these for a while, and we moved the maillist?

2023-08-15 15:09 UTC, gctucker commented on doc/_index.md
> +KCIDB:
Done

2023-08-15 15:19 UTC, spbnick approved these changes
Thanks a lot, Guillaume!

2023-08-16 07:51 UTC, merged

2023-08-18 20:23 UTC, gctucker commented
Thanks @spbnick for the reviews :)