Add flowchart about the status ownership and mention "running" around the absent status
kernelci/kcidb pull request #531
Opened 2024-06-06 18:06 UTC by tales-aparecida

CKI had this chart for a while in https://cki-project.org/docs/test-maintainers/status-meaning/ and it's been useful for explaining ownership!

2024-06-06 18:07 UTC, tales-aparecida commented
![image](https://github.com/kernelci/kcidb/assets/8299832/a0ac8662-04ba-475d-be7a-66b55447ba02)

2024-06-07 12:58 UTC, spbnick requested changes
Looks good to me mostly, thank you very much, Tales!

I left a couple comments inline, and do you think you could add a lead-in to that diagram, in a separate paragraph? Something like "Another way to organize status values is to put them into an execution outcome chart:"

2024-06-07 12:58 UTC, spbnick commented on doc/submitter_guide.md
> +execute, the system hasn't got to it yet, and so we have no data on anything, or it is still running.
Perhaps:
```suggestion
the absent "status" field, and means that the test is either only scheduled, or is still executing,
and so we have no status data yet.
```

2024-06-09 12:07 UTC, spbnick commented
Thanks a lot, Tales! Merging :+1:

2024-06-09 12:07 UTC, merged