doc/developer_build: add `Email notifications` section
kernelci/kcidb pull request #573
Opened 2024-09-12 11:59 UTC by JenySadadia

Explain KCIDB email notifications.

2024-09-12 12:00 UTC, JenySadadia commented
@spbnick Is it the correct place to mention email notifications or should I add this section to the submitter guide?

2024-09-13 05:24 UTC, JenySadadia commented
OK, I'll add a new page.

2024-09-23 13:17 UTC, spbnick requested changes
Thank you, Jeny! This looks good. I would only like to see better formatting of the Markdown source, where possible, as its whole point (ok, maybe not the whole, but most) is to be readable as is, and long lines are not that readable.

And another nitpick: since the subscriber guide did not exist before your commit, the correct commit subject would look something like this: `doc: Add a submitter guide`.

2024-09-23 13:17 UTC, spbnick commented on doc/subscriber_guide.md
> +Here is an example of such report:
Could you wrap the paragraphs on 78 columns?

2024-09-23 13:17 UTC, spbnick commented on doc/subscriber_guide.md
> +Such reports are useful for developers and maintainers to keep track of new failures with each new revision and can use these data for further required actions.
And here too, please.

2024-09-24 06:36 UTC, spbnick approved these changes
LGTM. Thank you, Jeny!

2024-09-24 08:54 UTC, merged